name: fitur_volunteer
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  get: ^4.6.5

  # chewie:
  # video_player:
  readmore: ^2.1.0
  file_picker: ^5.3.2
  image_picker: ^0.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
